[package]
name = "recipes"
version = "0.1.0"
edition = "2018"

[dependencies]
fltk = "1.1" # GUI library
semver = "1.0" # Checking versions of github releases

[profile.release]
codegen-units = 1
lto = true
