[package]
name = "recipes"
version = "0.1.0"
edition = "2018"

[dependencies]
eframe = "0.14" # GUI library
generational-arena = "0.2" # Pool of all recipes
semver = "1.0" # Checking versions of github releases
sublime_fuzzy = "0.7" # Fuzzy finding recipes by search key
humantime = "2.1" # Formatting recipe time estimates

[profile.release]
codegen-units = 1
lto = true
