[package]
name = "recipes"
version = "0.1.0"
edition = "2018"

[dependencies]
eframe = "0.14" # GUI library
generational-arena = "0.2" # Pool of all recipes
semver = "1.0" # Checking versions of github releases

[profile.release]
codegen-units = 1
lto = true
