[package]
name = "recipier"
version = "0.1.0"
edition = "2018"

[dependencies]
eframe = "0.14" # GUI library
generational-arena = { version = "0.2", features = ["serde"] } # Pool of all recipes
semver = "1.0" # Checking versions of github releases
sublime_fuzzy = "0.7" # Fuzzy finding recipes by search key
humantime = "2.1" # Formatting recipe time estimates
serde = { version = "1.0", features = ["derive"] } # Saving all recipes
serde_json = "1.0" # Saving recipes and eventually github API responses
image = "0.23" # For decoding image formats

[profile.release]
codegen-units = 1
lto = true
