name: Release Build
on:
  push:
    tags:
      - 'v[0-9]+.*'


env:
  CARGO_TERM_COLOR: always

jobs: 
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: Release $tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: install gtk+3 on ubuntu
        run:  |
                 if [ "$RUNNER_OS" == "Linux" ]; then
                      sudo apt-get install -y libgtk-3-dev
                 elif [ "$RUNNER_OS" == "Windows" ]; then
                      echo "Not installing GTK+3, not needed"
                 else
                      echo "Not installing GTK+3, not needed"
                 fi
        shell: bash
      
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: recipier
          tar: none
          zip: all
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
